import Navbar from "./Navbar/Navbar";
import Login from "./Login/Login";
import Signup from "./Signup/Signup";
import DocUploader from "./Requirements/DocUploader";
import Requirements from "./Requirements/Requirements";
import SideBar from "./Dashboard/SideBar";
import Dashboard from "./Dashboard/Dashboard";
import Vehicle from "./Vehicle/Vehicle";
import Earnings from "./Earnings/Earnings";
import TripManage from "./TripManage/TripManage";
import Profile from "./Profile/profile";
import Chat from "./Chat/Chat";
export { Navbar, Login, Signup, DocUploader, Requirements, SideBar, Dashboard, Vehicle, Earnings, TripManage, Profile, Chat };
